name: Docs
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up our JDK environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Build Storytale
        run: ./gradlew jsBrowserStoriesProductionExecutableDistribution
      - name: Add CNAME
        run: echo "ui.controlresell.com" > ui/build/dist/js/StoriesProductionExecutable/CNAME
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ui/build/dist/js/StoriesProductionExecutable
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
